apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      receiver: 'discord-webhook'
    receivers:
      - name: 'discord-webhook'
        webhook_configs:
          - url: 'https://discord.com/api/webhooks/your-webhook-url'
            send_resolved: true
            message: 'Alert triggered: {{ .CommonLabels.alertname }}\nSeverity: {{ .CommonLabels.severity }}\nDescription: {{ .Annotations.description }}'
