prometheus:
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager
        port: web
  rules:
    alert.rules:
      - /etc/prometheus/alert.rules.yml


server:
  persistentVolume:
    enabled: true
    size: 10Gi


# adminPassword: "admin123"
# datasources:
#   datasources.yaml:
#     apiVersion: 1
#     datasources:
#       - name: Prometheus
#         type: prometheus
#         access: proxy
#         url: http://prometheus-server.monitoring.svc.cluster.local