apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-alerts
  namespace: monitoring
  labels:
    prometheus: prometheus
    role: alert-rules
spec:
  groups:
    - name: example-alerts
      rules:
        # Alerte si un pod ne fonctionne pas (0 pods en "running")
        - alert: NoPodsRunning
          expr: kube_pod_status_phase{phase="Running"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "No pods are running"
            description: "There are no pods running in the cluster."

        # Alerte si l'utilisation de CPU dépasse un certain seuil (par exemple 80%)
        - alert: HighCpuUsage
          expr: (sum(rate(container_cpu_usage_seconds_total{container!="",container!="POD"}[5m])) by (pod)) > 0.8
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "High CPU usage"
            description: "CPU usage for a pod is above 80%."
            
        # Alerte si l'utilisation de la mémoire dépasse un certain seuil (par exemple 1Gi)
        - alert: HighMemoryUsage
          expr: (sum(container_memory_usage_bytes{container!="",container!="POD"}[5m])) by (pod) > 1073741824
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "High memory usage"
            description: "Memory usage for a pod is above 1Gi."

        - alert: DiscordTestAlert
          expr: vector(1) == 1
          labels:
            severity: test
          annotations:
            summary: "Test Alert Discord"
            description: "This is a test alert to check the Discord webhook."