apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-deployment
  namespace: default
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.25.0
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yaml"
          ports:
            - containerPort: 9093
          volumeMounts:
          - name: config-volume
            mountPath: /etc/alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-prometheus-alertmanager