apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat-deployment
  namespace: default
  labels:
    app: webgoat
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
      - name: webgoat
        image: enriquitotupapi/webgoat:main
        ports:
        - containerPort: 8080 
        - containerPort: 9090 
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"