apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat-deployment
  namespace: default
  labels:
    app: webgoat
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/WebGoat/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: webgoat
        image: enriquitotupapi/webgoat:main
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"